name: pyramid
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.0.1
  - h5py=3.8.0
  - python-graphviz=0.20.1
  - pip:
    - numpy==1.25.2
    - matplotlib==3.8.0
    - pyyaml==6.0
    - pyzmq==25.1.1
    - scipy==1.11.4